# Logistic Regression Model

In [93]:
#Check dataframe
df_1.head()

Adult                              Belongs To Collection      Budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000.0   
1  False                                                NaN  65000000.0   
3  False                                                NaN  16000000.0   
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0.0   
5  False                                                NaN  60000000.0   

                                              Genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                     [{'id': 35, 'name': 'Comedy'}]   
5  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...   

                               Homepage     ID    IMDB_id Original Language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en   
1                                   NaN   8844  tt0113497                en   
3                                   NaN  31357  tt0114885                en   
4                                   NaN  11862  tt0113041                en   
5                                   NaN    949  tt0113277                en   

                Original Title  \
0                    Toy Story   
1                      Jumanji   
3            Waiting to Exhale   
4  Father of the Bride Part II   
5                         Heat   

                                            Overview  ...  Family Fantasy  \
0  Led by Woody, Andy's toys live happily in his ...  ...       0       0   
1  When siblings Judy and Peter discover an encha...  ...       0       0   
3  Cheated on, mistreated and stepped on, the wom...  ...       0       0   
4  Just when George Banks has recovered from his ...  ...       0       0   
5  Obsessive master thief, Neil McCauley leads a ...  ...       0       0   

  Horror Mystery Romance  Science Fiction  Thriller Decile Rank  \
0      0       0       0                0         0         9.0   
1      0       0       0                0         0         9.0   
3      0       0       0                0         0         7.0   
4      0       0       0                0         0         7.0   
5      0       0       0                0         0         9.0   

  Over 5 Million Over 1 Million  
0              1              1  
1              1              1  
3              1              1  
4              1              1  
5              1              1  

[5 rows x 45 columns]

In [94]:
#Confirms Data Types 
df_1.dtypes

Adult                     object
Belongs To Collection     object
Budget                   float64
Genres                    object
Homepage                  object
ID                        object
IMDB_id                   object
Original Language         object
Original Title            object
Overview                  object
Popularity               float64
Poster Path               object
Production Companies      object
Production Countries      object
Release Date              object
Revenue                  float64
Runtime                  float64
Spoken Languages          object
Status                    object
Tagline                   object
Title                     object
Video                     object
Vote Average             float64
Vote Count               float64
Month                    float64
Season Released          float64
Primary Genre             object
List of Genres            object
Action                     uint8
Adventure                  uint8
Animation 

In [95]:
#Sets new dataframe for different model
df_2 = df_1
df_2.head()

Adult                              Belongs To Collection      Budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000.0   
1  False                                                NaN  65000000.0   
3  False                                                NaN  16000000.0   
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0.0   
5  False                                                NaN  60000000.0   

                                              Genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                     [{'id': 35, 'name': 'Comedy'}]   
5  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...   

                               Homepage     ID    IMDB_id Original Language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en   
1                                   NaN   8844  tt0113497                en   
3                                   NaN  31357  tt0114885                en   
4                                   NaN  11862  tt0113041                en   
5                                   NaN    949  tt0113277                en   

                Original Title  \
0                    Toy Story   
1                      Jumanji   
3            Waiting to Exhale   
4  Father of the Bride Part II   
5                         Heat   

                                            Overview  ...  Family Fantasy  \
0  Led by Woody, Andy's toys live happily in his ...  ...       0       0   
1  When siblings Judy and Peter discover an encha...  ...       0       0   
3  Cheated on, mistreated and stepped on, the wom...  ...       0       0   
4  Just when George Banks has recovered from his ...  ...       0       0   
5  Obsessive master thief, Neil McCauley leads a ...  ...       0       0   

  Horror Mystery Romance  Science Fiction  Thriller Decile Rank  \
0      0       0       0                0         0         9.0   
1      0       0       0                0         0         9.0   
3      0       0       0                0         0         7.0   
4      0       0       0                0         0         7.0   
5      0       0       0                0         0         9.0   

  Over 5 Million Over 1 Million  
0              1              1  
1              1              1  
3              1              1  
4              1              1  
5              1              1  

[5 rows x 45 columns]

In [ ]:
#double check movie with 0 revenue

In [96]:
#Set X and Y variables
X3 = df_2[['Popularity', 'Budget', 'Runtime', 'Vote Average', 'Vote Count', 'Season Released']]
y3 = df_2['Revenue']

In [97]:
#Confirms all nulls in specified dataframe columns gone
df_2.isnull().sum()

Adult                       0
Belongs To Collection    5725
Budget                      0
Genres                      0
Homepage                 4865
ID                          0
IMDB_id                     0
Original Language           0
Original Title              0
Overview                   15
Popularity                  0
Poster Path                 0
Production Companies        0
Production Countries        0
Release Date                0
Revenue                     0
Runtime                     0
Spoken Languages            0
Status                      1
Tagline                  1389
Title                       0
Video                       0
Vote Average                0
Vote Count                  0
Month                       0
Season Released             0
Primary Genre               0
List of Genres              0
Action                      0
Adventure                   0
Animation                   0
Comedy                      0
Crime                       0
Documentar

In [98]:
X3.dtypes

Popularity         float64
Budget             float64
Runtime            float64
Vote Average       float64
Vote Count         float64
Season Released    float64
dtype: object

In [99]:
y3.dtypes

dtype('float64')

In [100]:
#Set X and Y variables for LogReg
X3 = df_2[['Popularity', 'Budget', 'Runtime', 'Vote Average', 'Vote Count', 'Season Released']]
y3 = df_2[['Over 5 Million']]

In [101]:
#Train/test split
lr1X_train, lr1X_test, lr1y_train, lr1y_test = train_test_split(X3, y3, random_state=2)

In [102]:
#Fit Log Reg Model
logreg = LogisticRegression()
lr_model = logreg.fit(lr1X_train, lr1y_train)

C:\Users\taylo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\taylo\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [103]:
#Check Model score
lr_model.score(lr1X_train, lr1y_train)

0.6986275964391692

In [104]:
#Checks model score
lr_model.score(lr1X_test, lr1y_test)

0.7046718576195773

In [105]:
#Checks model coefficients
lr_model.coef_

array([[ 7.34542356e-14,  1.00768387e-07, -4.14185303e-13,
        -2.60669750e-14,  8.44376037e-12, -1.92557095e-14]])

In [106]:
#Set predictions
y_predict_lr = lr_model.predict(lr1X_test)

In [107]:
y_predict_lr.shape

(1798,)

In [108]:
lr1y_test.shape

(1798, 1)

In [109]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [110]:
tn, fp, fn, tp = confusion_matrix(lr1y_test, y_predict_lr).ravel()
tn, fp, fn, tp

(31, 530, 1, 1236)

In [111]:
# Python script for confusion matrix creation. 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
actual = lr1y_test
predicted = y_predict_lr
results = confusion_matrix(actual, predicted) 
print('Confusion Matrix :')
print(results) 
print('Accuracy Score :'),accuracy_score(actual, predicted) 
print('Report : ')
print(classification_report(actual, predicted))

Confusion Matrix :
[[  31  530]
 [   1 1236]]
Accuracy Score :
Report : 
              precision    recall  f1-score   support

           0       0.97      0.06      0.10       561
           1       0.70      1.00      0.82      1237

   micro avg       0.70      0.70      0.70      1798
   macro avg       0.83      0.53      0.46      1798
weighted avg       0.78      0.70      0.60      1798



In [112]:
print('Mean Absolute Error:', metrics.mean_absolute_error(lr1y_test, y_predict_lr))  
print('Mean Squared Error:', metrics.mean_squared_error(lr1y_test, y_predict_lr))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(lr1y_test, y_predict_lr)))

Mean Absolute Error: 0.2953281423804227
Mean Squared Error: 0.2953281423804227
Root Mean Squared Error: 0.5434410201488499


In [113]:
lm_logreg = sm.OLS(lr1y_train, lr1X_train)
lm_logreg_results = lm_logreg.fit()
print(lm_logreg_results.summary())

                            OLS Regression Results                            
Dep. Variable:         Over 5 Million   R-squared:                       0.727
Model:                            OLS   Adj. R-squared:                  0.726
Method:                 Least Squares   F-statistic:                     2388.
Date:                Tue, 27 Aug 2019   Prob (F-statistic):               0.00
Time:                        01:02:00   Log-Likelihood:                -3101.7
No. Observations:                5392   AIC:                             6215.
Df Residuals:                    5386   BIC:                             6255.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Popularity          0.0031      0.001     

In [ ]:
Model for $1 million threshold

In [115]:
#Checks number of movies with over $1 mill Revenue
df_2['Over 1 Million'].value_counts()

1    5886
0    1304
Name: Over 1 Million, dtype: int64

In [117]:
#Prints df_2 shape before and after droping nulls
print(df_2.shape)
df_2.dropna(subset=['Popularity', 'Budget', 'Runtime', 'Vote Average', 'Vote Count', 'Season Released', 'Revenue', 'Over 1 Million'] , inplace = True)
print(df_2.shape)

(7190, 45)
(7190, 45)


In [118]:
#Confirms all nulls in specified dataframe columns gone
df_2.isnull().sum()

Adult                       0
Belongs To Collection    5725
Budget                      0
Genres                      0
Homepage                 4865
ID                          0
IMDB_id                     0
Original Language           0
Original Title              0
Overview                   15
Popularity                  0
Poster Path                 0
Production Companies        0
Production Countries        0
Release Date                0
Revenue                     0
Runtime                     0
Spoken Languages            0
Status                      1
Tagline                  1389
Title                       0
Video                       0
Vote Average                0
Vote Count                  0
Month                       0
Season Released             0
Primary Genre               0
List of Genres              0
Action                      0
Adventure                   0
Animation                   0
Comedy                      0
Crime                       0
Documentar

In [119]:
#Confirms Over 1 Million is Object
df_2[['Over 1 Million']].dtypes

Over 1 Million    int64
dtype: object

In [120]:
#Set X and Y variables for LogReg
X3 = df_2[['Popularity', 'Budget', 'Runtime', 'Vote Average', 'Vote Count', 'Season Released']]
y3a = df_2[['Over 1 Million']]

In [121]:
#Train/test split
lr2X_train, lr2X_test, lr2y_train, lr2y_test = train_test_split(X3, y3a, random_state=2)

In [122]:
#Fit Log Reg Model
logreg = LogisticRegression()
lr_model_2 = logreg.fit(lr2X_train, lr2y_train)

C:\Users\taylo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\taylo\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [123]:
#Check Model score
lr_model_2.score(lr2X_train, lr2y_train)

0.8158382789317508

In [124]:
lr_model_2.score(lr2X_test, lr2y_test)

0.8270300333704116

In [128]:
#Checks model coefficients
lr_model_2.coef_

array([[5.80273614e-13, 1.96931577e-07, 5.89204278e-12, 3.63922869e-13,
        2.77066556e-11, 1.29341450e-13]])

In [130]:
#Set predictions
y_predict_lr_2 = lr_model_2.predict(lr2X_test)

In [131]:
# Python script for confusion matrix creation. 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
actual = lr2y_test
predicted = y_predict_lr_2
results = confusion_matrix(actual, predicted) 
print('Confusion Matrix :')
print(results) 
print('Accuracy Score :'),accuracy_score(actual, predicted) 
print('Report : ')
print(classification_report(actual, predicted))

Confusion Matrix :
[[   0  311]
 [   0 1487]]
Accuracy Score :
Report : 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       311
           1       0.83      1.00      0.91      1487

   micro avg       0.83      0.83      0.83      1798
   macro avg       0.41      0.50      0.45      1798
weighted avg       0.68      0.83      0.75      1798



C:\Users\taylo\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\taylo\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\taylo\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
